### ISSUE TITLE
Formular preguntas para la entrevista

### ISSUE THREAD

**Issue by dayaGuerra** [dayaGuerra/LIM008-social-network#1]
* Las preguntas no deben de brindar alternativas  y no deben de ser especificas.

* Preguntas que no sean incomodas.

* Enfocarnos en formularlas según lo que nos piden en el proyecto.

* Deben de ser formuladas a personas que tenganun emprendimiento social o sean parte de un emprendimiento social.

**Comment by JanetGM** [comment]
Las 5 preguntas 👍 
1-¿Qué problemas frecuentes encuentras en tu día a día como dueño del emprendimiento social?
2-¿Cuáles son los pasos que se siguen para reclutar personas que participen en un proyecto y cuánto tiempo lleva conseguirlo?
3-¿Qué datos te interesaría saber de los participantes para incluirlos en tus proyectos?
-----------------------Ahora para los Participantes---------------------------------------------------
4-¿Que información consideras importante saber  de las organizaciones y proyectos sociales para que te unas a ellos ?
5-Cuéntame como fue tu ultima experiencia buscando un proyecto social al cual querías unirte.

**Comment by dayaGuerra** [comment]
| Emprendedores sociales |  
1. | ¿Qué ideas vienen a ti cuando hablamos de una red social para emprendedores sociales?
2. | ¿Es difícil para ti encontrar personas que tengan las misma pasión por ayudar al prójimo?
3. | Con respecto a otros usuarios ¿Que tipo de intereses personales te gustaría encontrar en la red social?

  | Participantes del emprendimiento social |  
4. | ¿Alguna vez te ha interesado buscar un lugar donde puedas ser voluntario para ayudar a alguien?
5. | ¿Qué tan difícil ha sido para ti encontrar un lugar donde sabes que puedes ayudar y a la par puedas crecer como persona?

**Comment by cinthyasegura** [comment]
Preguntas:
-- | -- | --
1. | ¿Como se te ocurrio crear tu emprendimiento, hiciste uso de alguna red social?
2. | ¿Crees que te hubiera sido de ayuda tener una red social cuando iniciabas con la creacion de tu proyecto? Por que?
3. | ¿Se te ha sido complicado poder encontrar colaboradores/ cofundadores  que crean en tu proyecto?
  | Participantes del emprendimiento social |  
4. | ¿Que es lo que te gustaria ver/hacer en una red social creada para emprendedores |   |   |   |  
5. | ¿Has utilizado alguna red social para buscar inspiracion y/o recomendaciones sobre emprendimiento?
  | EXTRA
6. | ¿Que redes sociales utilizas para compartir informacion sobre tu empredimiento y por que? |   |   |   |
